verifyDepsBeforeRun: install
packages:
  - "packages/*"
  - "docs/**"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89
  vitest: 4.1.10
  vite-plus: 0.0.0-commit.9855245a469b178066c25a5d45c971c130565d89
  esbuild: ^0.28.0
  typescript: ^6.0.2
  react: ^19.2.5
  react-dom: ^19.2.5
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@types/node": ^25.6.0
  '@vitest/browser-playwright': 4.1.10
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
